# Generated by Django 5.1.1 on 2024-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_avalable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratind',
            field=models.FloatField(default=0.0),
        ),
    ]
