# Generated by Django 5.1.1 on 2024-11-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_is_avalable_alter_product_ratind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderssssss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=70)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
